import type { User, Department, Asset, RolePermissions, UserRole } from "./types";

export const mockUsers: User[] = [
  { id: "U001", nome: "Mario", cognome: "Rossi", email: "mario.rossi@azienda.it", reparto: "IT", sede: "Milano", ruolo: "Admin", password: "Admin123!" },
  { id: "U002", nome: "Laura", cognome: "Bianchi", email: "laura.bianchi@azienda.it", reparto: "Marketing", sede: "Milano", ruolo: "Manager", password: "Manager123!" },
  { id: "U003", nome: "Giulia", cognome: "Verdi", email: "giulia.verdi@azienda.it", reparto: "IT", sede: "Milano", ruolo: "Manager", password: "Manager123!" },
  { id: "U004", nome: "Marco", cognome: "Neri", email: "marco.neri@azienda.it", reparto: "Vendite", sede: "Roma", ruolo: "Viewer", password: "Viewer123!" },
  { id: "U005", nome: "Anna", cognome: "Ferrari", email: "anna.ferrari@azienda.it", reparto: "HR", sede: "Milano", ruolo: "Manager", password: "Manager123!" },
  { id: "U006", nome: "Paolo", cognome: "Gialli", email: "paolo.gialli@azienda.it", reparto: "IT", sede: "Roma", ruolo: "Admin", password: "Admin123!" },
  { id: "U007", nome: "Sara", cognome: "Colombo", email: "sara.colombo@azienda.it", reparto: "Amministrazione", sede: "Milano", ruolo: "Viewer", password: "Viewer123!" },
  { id: "U008", nome: "Luca", cognome: "Marino", email: "luca.marino@azienda.it", reparto: "Vendite", sede: "Napoli", ruolo: "Viewer", password: "Viewer123!" },
  { id: "U009", nome: "Chiara", cognome: "Ricci", email: "chiara.ricci@azienda.it", reparto: "Direzione", sede: "Milano", ruolo: "Manager", password: "Manager123!" },
  { id: "U010", nome: "Andrea", cognome: "Moretti", email: "andrea.moretti@azienda.it", reparto: "Produzione", sede: "Torino", ruolo: "Viewer", password: "Viewer123!" },
];

export const mockDepartments: Department[] = [
  { id: "D001", nome: "IT", sede: "Milano", responsabile: "Mario Rossi", numDipendenti: 12 },
  { id: "D002", nome: "Marketing", sede: "Milano", responsabile: "Laura Bianchi", numDipendenti: 8 },
  { id: "D003", nome: "Vendite", sede: "Roma", responsabile: "Marco Neri", numDipendenti: 10 },
  { id: "D004", nome: "HR", sede: "Milano", responsabile: "Anna Ferrari", numDipendenti: 6 },
  { id: "D005", nome: "Amministrazione", sede: "Milano", responsabile: "Sara Colombo", numDipendenti: 5 },
  { id: "D006", nome: "Direzione", sede: "Milano", responsabile: "Chiara Ricci", numDipendenti: 4 },
  { id: "D007", nome: "Produzione", sede: "Torino", responsabile: "Andrea Moretti", numDipendenti: 15 },
  { id: "D008", nome: "Vendite", sede: "Napoli", responsabile: "Luca Marino", numDipendenti: 7 },
];

export const mockAssets: Asset[] = [
  { id: "A001", nome: "MacBook Pro 16\"", categoria: "Laptop", marca: "Apple", modello: "MacBook Pro M3 Max", numeroSeriale: "ASSET-SN-2024-001", dataAcquisto: "15/01/2024", costo: 3299, garanziaMesi: 24, stato: "In uso", assegnatoA: "Mario Rossi", reparto: "IT" },
  { id: "A002", nome: "MacBook Pro 14\"", categoria: "Laptop", marca: "Apple", modello: "MacBook Pro M3 Pro", numeroSeriale: "ASSET-SN-2024-002", dataAcquisto: "15/01/2024", costo: 2499, garanziaMesi: 24, stato: "In uso", assegnatoA: "Laura Bianchi", reparto: "Marketing" },
  { id: "A003", nome: "Dell XPS 15", categoria: "Laptop", marca: "Dell", modello: "XPS 15 9530", numeroSeriale: "ASSET-SN-2024-003", dataAcquisto: "20/01/2024", costo: 1450, garanziaMesi: 24, stato: "In uso", assegnatoA: "Giulia Verdi", reparto: "IT" },
  { id: "A004", nome: "Lenovo ThinkPad X1 Carbon", categoria: "Laptop", marca: "Lenovo", modello: "X1 Carbon Gen 11", numeroSeriale: "ASSET-SN-2024-004", dataAcquisto: "01/02/2024", costo: 1799, garanziaMesi: 36, stato: "In uso", assegnatoA: "Marco Neri", reparto: "Vendite" },
  { id: "A005", nome: "HP EliteBook 840", categoria: "Laptop", marca: "HP", modello: "EliteBook 840 G10", numeroSeriale: "ASSET-SN-2024-005", dataAcquisto: "01/02/2024", costo: 1350, garanziaMesi: 36, stato: "Disponibile", assegnatoA: null, reparto: null },
  { id: "A006", nome: "Dell Latitude 5540", categoria: "Laptop", marca: "Dell", modello: "Latitude 5540", numeroSeriale: "ASSET-SN-2024-006", dataAcquisto: "15/03/2024", costo: 1150, garanziaMesi: 24, stato: "In manutenzione", assegnatoA: null, reparto: null },
  { id: "A007", nome: "Lenovo ThinkPad T14s", categoria: "Laptop", marca: "Lenovo", modello: "T14s Gen 4", numeroSeriale: "ASSET-SN-2023-010", dataAcquisto: "10/06/2023", costo: 1299, garanziaMesi: 24, stato: "Dismesso", assegnatoA: null, reparto: null },
  { id: "A008", nome: "Dell UltraSharp 27\"", categoria: "Monitor", marca: "Dell", modello: "U2723QE", numeroSeriale: "ASSET-SN-2024-008", dataAcquisto: "15/01/2024", costo: 589, garanziaMesi: 36, stato: "In uso", assegnatoA: "Mario Rossi", reparto: "IT" },
  { id: "A009", nome: "Dell UltraSharp 27\"", categoria: "Monitor", marca: "Dell", modello: "U2723QE", numeroSeriale: "ASSET-SN-2024-009", dataAcquisto: "15/01/2024", costo: 589, garanziaMesi: 36, stato: "In uso", assegnatoA: "Giulia Verdi", reparto: "IT" },
  { id: "A010", nome: "LG 4K 32\"", categoria: "Monitor", marca: "LG", modello: "32UN880-B", numeroSeriale: "ASSET-SN-2024-010", dataAcquisto: "20/01/2024", costo: 649, garanziaMesi: 36, stato: "In uso", assegnatoA: "Laura Bianchi", reparto: "Marketing" },
  { id: "A011", nome: "Samsung ViewFinity 27\"", categoria: "Monitor", marca: "Samsung", modello: "S80UA", numeroSeriale: "ASSET-SN-2024-011", dataAcquisto: "01/03/2024", costo: 449, garanziaMesi: 24, stato: "Disponibile", assegnatoA: null, reparto: null },
  { id: "A012", nome: "BenQ PD2700U", categoria: "Monitor", marca: "BenQ", modello: "PD2700U", numeroSeriale: "ASSET-SN-2023-012", dataAcquisto: "05/05/2023", costo: 529, garanziaMesi: 36, stato: "In uso", assegnatoA: "Chiara Ricci", reparto: "Direzione" },
  { id: "A013", nome: "iPhone 15 Pro", categoria: "Smartphone", marca: "Apple", modello: "iPhone 15 Pro 256GB", numeroSeriale: "ASSET-SN-2024-013", dataAcquisto: "01/10/2024", costo: 1239, garanziaMesi: 24, stato: "In uso", assegnatoA: "Chiara Ricci", reparto: "Direzione" },
  { id: "A014", nome: "iPhone 15", categoria: "Smartphone", marca: "Apple", modello: "iPhone 15 128GB", numeroSeriale: "ASSET-SN-2024-014", dataAcquisto: "01/10/2024", costo: 979, garanziaMesi: 24, stato: "In uso", assegnatoA: "Marco Neri", reparto: "Vendite" },
  { id: "A015", nome: "Samsung Galaxy S24", categoria: "Smartphone", marca: "Samsung", modello: "Galaxy S24 256GB", numeroSeriale: "ASSET-SN-2024-015", dataAcquisto: "15/02/2024", costo: 899, garanziaMesi: 24, stato: "In uso", assegnatoA: "Luca Marino", reparto: "Vendite" },
  { id: "A016", nome: "Samsung Galaxy A55", categoria: "Smartphone", marca: "Samsung", modello: "Galaxy A55 5G", numeroSeriale: "ASSET-SN-2025-016", dataAcquisto: "10/01/2025", costo: 459, garanziaMesi: 24, stato: "Disponibile", assegnatoA: null, reparto: null },
  { id: "A017", nome: "iPad Pro 12.9\"", categoria: "Tablet", marca: "Apple", modello: "iPad Pro M2 12.9\"", numeroSeriale: "ASSET-SN-2024-017", dataAcquisto: "15/03/2024", costo: 1449, garanziaMesi: 24, stato: "In uso", assegnatoA: "Laura Bianchi", reparto: "Marketing" },
  { id: "A018", nome: "Samsung Galaxy Tab S9", categoria: "Tablet", marca: "Samsung", modello: "Galaxy Tab S9 FE", numeroSeriale: "ASSET-SN-2024-018", dataAcquisto: "15/03/2024", costo: 549, garanziaMesi: 24, stato: "In uso", assegnatoA: "Anna Ferrari", reparto: "HR" },
  { id: "A019", nome: "iPad Air", categoria: "Tablet", marca: "Apple", modello: "iPad Air M1", numeroSeriale: "ASSET-SN-2023-019", dataAcquisto: "01/09/2023", costo: 799, garanziaMesi: 24, stato: "Disponibile", assegnatoA: null, reparto: null },
  { id: "A020", nome: "HP LaserJet Pro", categoria: "Stampanti", marca: "HP", modello: "LaserJet Pro M404dn", numeroSeriale: "ASSET-SN-2023-020", dataAcquisto: "01/04/2023", costo: 299, garanziaMesi: 12, stato: "In uso", assegnatoA: null, reparto: "IT", ubicazione: "Sala stampa" },
  { id: "A021", nome: "Epson EcoTank", categoria: "Stampanti", marca: "Epson", modello: "ET-4850", numeroSeriale: "ASSET-SN-2024-021", dataAcquisto: "01/06/2024", costo: 399, garanziaMesi: 24, stato: "In uso", assegnatoA: null, reparto: "Marketing" },
  { id: "A022", nome: "Brother MFC", categoria: "Stampanti", marca: "Brother", modello: "MFC-L3770CDW", numeroSeriale: "ASSET-SN-2024-022", dataAcquisto: "01/06/2024", costo: 449, garanziaMesi: 24, stato: "In manutenzione", assegnatoA: null, reparto: "HR" },
  { id: "A023", nome: "Server Principale", categoria: "Server", marca: "Dell", modello: "PowerEdge R750", numeroSeriale: "ASSET-SN-2023-023", dataAcquisto: "15/01/2023", costo: 8500, garanziaMesi: 36, stato: "In uso", assegnatoA: null, reparto: null, ubicazione: "Sala Server Milano" },
  { id: "A024", nome: "Server Backup", categoria: "Server", marca: "HPE", modello: "ProLiant DL380 Gen10", numeroSeriale: "ASSET-SN-2023-024", dataAcquisto: "15/01/2023", costo: 6200, garanziaMesi: 36, stato: "In uso", assegnatoA: null, reparto: null, ubicazione: "Sala Server Milano" },
  { id: "A025", nome: "Server Dev/Test", categoria: "Server", marca: "Dell", modello: "PowerEdge T550", numeroSeriale: "ASSET-SN-2024-025", dataAcquisto: "01/03/2024", costo: 4800, garanziaMesi: 36, stato: "In uso", assegnatoA: null, reparto: null, ubicazione: "Sala Server Roma" },
  { id: "A026", nome: "Docking Station USB-C", categoria: "Accessori IT", marca: "CalDigit", modello: "TS4", numeroSeriale: "ASSET-SN-2024-026", dataAcquisto: "15/01/2024", costo: 379, garanziaMesi: 24, stato: "In uso", assegnatoA: "Mario Rossi", reparto: "IT" },
  { id: "A027", nome: "Tastiera Wireless", categoria: "Accessori IT", marca: "Logitech", modello: "MX Keys S", numeroSeriale: "ASSET-SN-2024-027", dataAcquisto: "15/01/2024", costo: 119, garanziaMesi: 24, stato: "In uso", assegnatoA: "Laura Bianchi", reparto: "Marketing" },
  { id: "A028", nome: "Mouse Ergonomico", categoria: "Accessori IT", marca: "Logitech", modello: "MX Master 3S", numeroSeriale: "ASSET-SN-2024-028", dataAcquisto: "15/01/2024", costo: 109, garanziaMesi: 24, stato: "In uso", assegnatoA: "Giulia Verdi", reparto: "IT" },
  { id: "A029", nome: "Cuffie Noise-Cancelling", categoria: "Accessori IT", marca: "Sony", modello: "WH-1000XM5", numeroSeriale: "ASSET-SN-2024-029", dataAcquisto: "01/03/2024", costo: 349, garanziaMesi: 24, stato: "In uso", assegnatoA: "Marco Neri", reparto: "Vendite" },
  { id: "A030", nome: "Webcam HD", categoria: "Accessori IT", marca: "Logitech", modello: "Brio 4K", numeroSeriale: "ASSET-SN-2024-030", dataAcquisto: "01/03/2024", costo: 199, garanziaMesi: 24, stato: "Disponibile", assegnatoA: null, reparto: null },
  { id: "A031", nome: "Router Principale", categoria: "Dispositivi di Rete", marca: "Cisco", modello: "ISR 4331", numeroSeriale: "ASSET-SN-2023-031", dataAcquisto: "01/02/2023", costo: 2800, garanziaMesi: 36, stato: "In uso", assegnatoA: null, reparto: null, ubicazione: "Sala Server Milano" },
  { id: "A032", nome: "Switch PoE 48p", categoria: "Dispositivi di Rete", marca: "Cisco", modello: "Catalyst 9200L", numeroSeriale: "ASSET-SN-2023-032", dataAcquisto: "01/02/2023", costo: 1950, garanziaMesi: 36, stato: "In uso", assegnatoA: null, reparto: null, ubicazione: "Sala Server Milano" },
  { id: "A033", nome: "Access Point Wi-Fi 6", categoria: "Dispositivi di Rete", marca: "Ubiquiti", modello: "UniFi U6 Pro", numeroSeriale: "ASSET-SN-2024-033", dataAcquisto: "01/04/2024", costo: 159, garanziaMesi: 24, stato: "In uso", assegnatoA: null, reparto: null, ubicazione: "Piano 2 — Milano" },
  { id: "A034", nome: "Access Point Wi-Fi 6", categoria: "Dispositivi di Rete", marca: "Ubiquiti", modello: "UniFi U6 Pro", numeroSeriale: "ASSET-SN-2024-034", dataAcquisto: "01/04/2024", costo: 159, garanziaMesi: 24, stato: "In uso", assegnatoA: null, reparto: null, ubicazione: "Piano 3 — Milano" },
];

export const rolePermissions: Record<UserRole, RolePermissions> = {
  Admin: {
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canAssign: true,
    canManageUsers: true,
    canAccessSettings: true,
    canViewDashboard: true,
    canViewCatalog: true,
    canViewReports: true,
  },
  Manager: {
    canCreate: true,
    canEdit: true,
    canDelete: false,
    canAssign: true,
    canManageUsers: false,
    canAccessSettings: false,
    canViewDashboard: true,
    canViewCatalog: true,
    canViewReports: true,
  },
  Viewer: {
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canAssign: false,
    canManageUsers: false,
    canAccessSettings: false,
    canViewDashboard: true,
    canViewCatalog: true,
    canViewReports: true,
  },
};
